= PCF Environment Access

== Account set up

. If you do not have an account yet, please see the instructor

== Target the Environment

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Login to Pivotal Cloudfoundry:
+
----
$ cf login -a https://api.devcloudwest.inbcu.com
----
+
Follow the prompts.  If prompted for an Org or a Space, select `OpenPlatform` and `ssotest` respectively.
Please note, that if you are prompted for an email, enter your SSO id, not your email (misleading).
+
. If you don't get prompted for an email/password or have other problems, you can also try:
+
----
$ cf login -a https://api.devcloudwest.inbcu.com -u <NBCU SSO> -p <password>
----
+


== Apps Manager UI

. An alternative to installing the CF CLI is via your PCF Apps Manager interface.

. Navigate in a web browser to https://apps.devcloudwest.inbcu.com

. Login to the interface with your SSO id and password.

. Click the 'Tools' link, and download the CLI matching your operating system
